### ISSUE TITLE
Failed download smalot/pdfparser

### ISSUE THREAD

**Issue by bastienff** [SowerPHP/extension-general#2]
Al instalar sowerphp (./sowerpkg.sh install -e "empresa app general" -W) da error al intentar descargar este paquete e interrumpe el proceso generado el log.

```
- Installing smalot/pdfparser (dev-master 31590f7)
Cloning 31590f7938a22f1c7fc4fb292611e3742a62ebaa
Failed to download smalot/pdfparser from source: The process "git clone --n$
Now trying to download from dist

-Installing smalot/pdfparser (dev-master 31590f7)
Loading from cache
```

**Comment by estebandelaf** [comment]
La dependencia no se estaba usando en la extensión, por lo cual la removí. Ahora deberías poder instalar sin problemas. Saludos!
